refactor: rewrite the init script
Signed-off-by: Tianling Shen <cnsztl@immortalwrt.org>

diff --git a/root/etc/init.d/unblockneteasemusic b/root/etc/init.d/unblockneteasemusic
--- a/root/etc/init.d/unblockneteasemusic
+++ b/root/etc/init.d/unblockneteasemusic
@@ -2,16 +2,34 @@
 # SPDX-License-Identifier: GPL-3.0-only
 # Copyright (C) 2019-2021 Tianling Shen <cnsztl@immortalwrt.org>
 
-START=92
+START=99
 STOP=10
 
 NAME="unblockneteasemusic"
 UPGRADE_CONF="/lib/upgrade/keep.d/$NAME"
 
-uci_get_by_type() {
-	local "ret"
-	ret="$(uci get "$NAME".@"$1"[0]."$2" 2>/dev/null)"
-	echo "${ret:=$3}"
+IPT_N="iptables -t nat"
+
+is_enabled() {
+	local enabled
+	config_get enabled "$1" "$2" "0"
+	if [ "$enabled" -eq "1" ]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+config_padding_arg() {
+	local value
+	config_get value "$1" "$2" $4
+	[ -n "$value" ] && export $(eval echo "$2")="$3 $value"
+}
+
+append_param_env() {
+	local value
+	config_get value "$1" "$2"
+	[ -n "$value" ] && export $(eval echo "$3")="$value"
 }
 
 uci_get_by_name() {
@@ -24,71 +42,83 @@ uci_get_by_name() {
 	echo "${ret:=$3}"
 }
 
-lan_addr="$(uci get network.lan.ipaddr)"
-
-enable="$(uci_get_by_type "$NAME" "enable" "0")"
-
-music_source="$(uci_get_by_type "$NAME" "music_source" "default")"
-
-[ "$(uci_get_by_type "$NAME" "enable_flac" "0")" = "1" ] && export ENABLE_FLAC="true"
-
-case "$(uci_get_by_type "$NAME" "replace_music_source" "dont_replace")" in
-"lower_than_192kbps") export MIN_BR="192000" ;;
-"lower_than_320kbps") export MIN_BR="320000" ;;
-"lower_than_999kbps") export MIN_BR="999000" ;;
-"replace_all") export MIN_BR="999999" ;;
-esac
-
-use_remote_qq_server="$(uci_get_by_type "$NAME" "use_remote_qq_server")"
-
-auto_update="$(uci_get_by_type "$NAME" "auto_update" "1")"
-update_time="$(uci_get_by_type "$NAME" "update_time" "3")"
-
-http_port="$(uci_get_by_type "$NAME" "http_port" "5200")"
-https_port="$(uci_get_by_type "$NAME" "https_port" "5201")"
-
-endpoint_url="$(uci_get_by_type "$NAME" "endpoint_url" "https://music.163.com")"
-hijack_ways="$(uci_get_by_type "$NAME" "hijack_ways" "use_ipset")"
-
-migu_cookie="$(uci_get_by_type "$NAME" "migu_cookie")"
-[ -n "${migu_cookie}" ] && export MIGU_COOKIE="${migu_cookie}"
-qq_cookie="$(uci_get_by_type "$NAME" "qq_cookie")"
-[ -n "${qq_cookie}" ] && export QQ_COOKIE="${qq_cookie}"
-youtube_key="$(uci_get_by_type "$NAME" "youtube_key")"
-[ -n "${youtube_key}" ] && export YOUTUBE_KEY="${youtube_key}"
-
-keep_core_when_upgrade="$(uci_get_by_type "$NAME" "keep_core_when_upgrade")"
-[ "$(uci_get_by_type "$NAME" "pub_access")" = "1" ] && addr="0.0.0.0" || addr="${lan_addr}"
-[ "$(uci_get_by_type "$NAME" "strict_mode")" = "1" ] && strict_mode="-s"
-
-netease_server_ip="$(uci_get_by_type "$NAME" "netease_server_ip")"
-[ -n "${netease_server_ip}" ] && netease_server_ip="-f ${netease_server_ip}"
-proxy_server_ip="$(uci_get_by_type "$NAME" "proxy_server_ip")"
-[ -n "${proxy_server_ip}" ] && proxy_server_ip="-u ${proxy_server_ip}"
-
-self_issue_cert_crt="$(uci_get_by_type "$NAME" "self_issue_cert_crt")"
-self_issue_cert_key="$(uci_get_by_type "$NAME" "self_issue_cert_key")"
-{ [ -n "{$self_issue_cert_crt}" ] && [ -n "${self_issue_cert_key}" ]; } && {
-	export SIGN_CERT="${self_issue_cert_crt}"
-	export SIGN_KEY="${self_issue_cert_key}"
-}
-
-set_ipset()
+start()
 {
-	if [ "${set_type}" = "start" ]; then
+	stop
+
+	config_load "$NAME"
+	is_enabled "config" "enable" || exit 1
+
+	local update_time
+	config_get update_time "config" "update_time" "3"
+	sed -i "/$NAME/d" /etc/crontabs/root
+	is_enabled "config" "auto_update" && echo "0 ${update_time} * * * /usr/share/$NAME/update.sh update_core" >> "/etc/crontabs/root"
+	echo "*/5 * * * * /usr/share/$NAME/log_check.sh" >> "/etc/crontabs/root"
+	/etc/init.d/cron restart > "/dev/null" 2>&1
+
+	[ ! -e "/usr/share/$NAME/core/app.js" ] && { rm -f "/usr/share/$NAME/local_ver"; sh "/usr/share/$NAME/update.sh" "update_core_non_restart"; }
+	[ ! -e "/usr/share/$NAME/core/app.js" ] && { echo "Core Not Found, please download it before starting." >> "/tmp/$NAME.log"; exit 1; }
+
+	local http_port https_port hijack_ways
+	config_get http_port "config" "http_port" "5200"
+	config_get https_port "config" "https_port" "5201"
+	config_get hijack_ways "config" "hijack_ways" "use_ipset"
+	[ "${hijack_ways}" = "use_hosts" ] && { http_port="80"; https_port="443"; }
+
+	local lan_addr
+	lan_addr="$(uci get network.lan.ipaddr)"
+	if is_enabled "config" "pub_access"; then
+		listen_addr="0.0.0.0"
+
+		iptables -I "INPUT" -p "tcp" --dport "${http_port}" -j "ACCEPT"
+		iptables -I "INPUT" -p "tcp" --dport "${https_port}" -j "ACCEPT"
+		echo "${http_port}:${https_port}" > "/tmp/$NAME.ports"
+
+		mkdir -p "/var/etc/"
+		echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
+	else
+		listen_addr="${lan_addr}"
+	fi
+
+	local music_source
+	config_get music_source "config" "music_source" "default"
+	[ "${music_source}" != "default" ] && music_source="-o ${music_source}"
+
+	is_enabled "config" "strict_mode" && strict_mode="-s"
+	config_padding_arg "config" "endpoint_url" "-e" "https://music.163.com"
+	config_padding_arg "config" "netease_server_ip" "-f"
+	config_padding_arg "config" "proxy_server_ip" "-u"
+
+	append_param_env "config" "migu_cookie" "MIGU_COOKIE"
+	append_param_env "config" "qq_cookie" "QQ_COOKIE"
+	append_param_env "config" "youtube_key" "YOUTUBE_KEY"
+	append_param_env "config" "self_issue_cert_crt" "SIGN_CERT"
+	append_param_env "config" "self_issue_cert_key" "SIGN_KEY"
+
+	is_enabled "config" "enable_flac" && export ENABLE_FLAC="true"
+	case "$(config_get "config" "replace_music_source")" in
+		"lower_than_192kbps") export MIN_BR="192000" ;;
+		"lower_than_320kbps") export MIN_BR="320000" ;;
+		"lower_than_999kbps") export MIN_BR="999000" ;;
+		"replace_all") export MIN_BR="999999" ;;
+	esac
+
+	node "/usr/share/$NAME/core/app.js" -a "${listen_addr}" -p "${http_port}":"${https_port}" ${music_source} ${endpoint_url} ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >"/tmp/$NAME.log" 2>&1 &
+
+	if [ "${hijack_ways}" = "use_ipset" ]; then
 		mkdir -p "/tmp/dnsmasq.d"
 		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
 		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
-dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
-ipset=/.music.163.com/neteasemusic
-ipset=/interface.music.163.com/neteasemusic
-ipset=/interface3.music.163.com/neteasemusic
-ipset=/apm.music.163.com/neteasemusic
-ipset=/apm3.music.163.com/neteasemusic
-ipset=/clientlog.music.163.com/neteasemusic
-ipset=/clientlog3.music.163.com/neteasemusic
+			dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
+			ipset=/.music.163.com/neteasemusic
+			ipset=/interface.music.163.com/neteasemusic
+			ipset=/interface3.music.163.com/neteasemusic
+			ipset=/apm.music.163.com/neteasemusic
+			ipset=/apm3.music.163.com/neteasemusic
+			ipset=/clientlog.music.163.com/neteasemusic
+			ipset=/clientlog3.music.163.com/neteasemusic
 		EOF
-		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1
+		/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
 
 		if ! ipset list "acl_neteasemusic_http" > "/dev/null"; then ipset create "acl_neteasemusic_http" hash:ip; fi
 		if ! ipset list "acl_neteasemusic_https" > "/dev/null"; then ipset create "acl_neteasemusic_https" hash:ip; fi
@@ -112,120 +142,54 @@ ipset=/clientlog3.music.163.com/neteasemusic
 			esac
 		done
 
-		if ! ipset list "neteasemusic" > "/dev/null"; then ipset create "neteasemusic" hash:ip; fi
+		ipset list "neteasemusic" > "/dev/null" || ipset create "neteasemusic" hash:ip
 		uclient-fetch -q -O- "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.data.*.ip.*' |sort -u |awk '{print "ipset add neteasemusic "$1}' |sh > "/dev/null" 2>&1
-		iptables -t "nat" -N "netease_cloud_music"
-		iptables -t "nat" -A "netease_cloud_music" -d "0.0.0.0/8" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "10.0.0.0/8" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "127.0.0.0/8" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "169.254.0.0/16" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "172.16.0.0/12" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "192.168.0.0/16" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "224.0.0.0/4" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -d "240.0.0.0/4" -j "RETURN"
-		iptables -t "nat" -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_http" "src" --dport "80" -j "REDIRECT" --to-ports "${http_port}"
-		iptables -t "nat" -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_https" "src" --dport "443" -j "REDIRECT" --to-ports "${https_port}"
-		iptables -t "nat" -I "PREROUTING" -p "tcp" -m "set" --match-set "neteasemusic" "dst" -j "netease_cloud_music"
-		[ -z "$(iptables -t "nat" -L "KOOLPROXY" | grep "UnblockMusic" | sed 's/\/.*//')" ] && iptables -t "nat" -I "KOOLPROXY" -m "set" --match-set "neteasemusic" "dst" -j "RETURN" -m "comment" --comment "KP for UnblockMusic"
+		$IPT_N -N "netease_cloud_music"
+		for local_addr in "0.0.0.0/8" "10.0.0.0/8" "127.0.0.0/8" "169.254.0.0/16" "172.16.0.0/12" "192.168.0.0/16" "224.0.0.0/4" "240.0.0.0/4"; do
+			$IPT_N -A "netease_cloud_music" -d "${local_addr}" -j "RETURN"
+		done
+		$IPT_N -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_http" "src" --dport "80" -j "REDIRECT" --to-ports "${http_port}"
+		$IPT_N -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_https" "src" --dport "443" -j "REDIRECT" --to-ports "${https_port}"
+		$IPT_N -I "PREROUTING" -p "tcp" -m "set" --match-set "neteasemusic" "dst" -j "netease_cloud_music"
+		$IPT_N -I "KOOLPROXY" -m "set" --match-set "neteasemusic" "dst" -j "RETURN" -m "comment" --comment "KP for UnblockMusic"
 
 		mkdir -p "/var/etc/"
 		echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
-	elif [ "${set_type}" = "stop" ]; then
-		iptables -t "nat" -D "PREROUTING" -p "tcp" -m set --match-set "neteasemusic" "dst" -j "netease_cloud_music"
-		iptables -t "nat" -D "KOOLPROXY" -m "set" --match-set "neteasemusic" "dst" -j "RETURN" -m "comment" --comment "KP for UnblockMusic"
-		iptables -t "nat" -F "netease_cloud_music"
-		iptables -t "nat" -X "netease_cloud_music"
-		ipset destroy "neteasemusic"
-		ipset destroy "acl_neteasemusic_http"
-		ipset destroy "acl_neteasemusic_https"
-
-		echo "" > "/var/etc/$NAME.include"
-		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
-		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1
-	fi
-}
-
-set_hosts()
-{
-	if [ "${set_type}" = "start" ]; then
+	elif [ "${hijack_ways}" = "use_hosts" ]; then
 		mkdir -p "/tmp/dnsmasq.d"
 		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
 		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
-dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
-address=/music.163.com/${lan_addr}
-address=/interface.music.163.com/${lan_addr}
-address=/interface3.music.163.com/${lan_addr}
-address=/apm.music.163.com/${lan_addr}
-address=/apm3.music.163.com/${lan_addr}
-address=/clientlog.music.163.com/${lan_addr}
-address=/clientlog3.music.163.com/${lan_addr}
-address=/music.httpdns.c.163.com/0.0.0.0
+			dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
+			address=/music.163.com/${lan_addr}
+			address=/interface.music.163.com/${lan_addr}
+			address=/interface3.music.163.com/${lan_addr}
+			address=/apm.music.163.com/${lan_addr}
+			address=/apm3.music.163.com/${lan_addr}
+			address=/clientlog.music.163.com/${lan_addr}
+			address=/clientlog3.music.163.com/${lan_addr}
+			address=/music.httpdns.c.163.com/0.0.0.0
 		EOF
-		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1
+		/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
 
 		ip route add "223.252.199.10" dev lo
-	elif [ "${set_type}" = "stop" ]; then
-		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
-		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1
-
-		ip route del "223.252.199.10"
 	fi
-}
-
-set_ports()
-{
-	if [ "${set_type}" = "start" ]; then
-		iptables -I "INPUT" -p "tcp" --dport "${http_port}" -j "ACCEPT"
-		iptables -I "INPUT" -p "tcp" --dport "${https_port}" -j "ACCEPT"
-
-		mkdir -p "/var/etc/"
-		echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
-	elif [ "${set_type}" = "stop" ]; then
-		iptables -D "INPUT" -p "tcp" --dport "${http_port}" -j "ACCEPT"
-		iptables -D "INPUT" -p "tcp" --dport "${https_port}" -j "ACCEPT"
-
-		echo "" > "/var/etc/$NAME.include"
-	fi
-}
-
-start()
-{
-	stop
-
-	[ "${enable}" -ne "1" ] && exit 0
-
-	sed -i "/$NAME/d" /etc/crontabs/root
-	[ "${auto_update}" -eq "1" ] && echo "0 ${update_time} * * * /usr/share/$NAME/update.sh update_core" >> "/etc/crontabs/root"
-	echo "*/5 * * * * /usr/share/$NAME/log_check.sh" >> "/etc/crontabs/root"
-	/etc/init.d/cron restart > "/dev/null" 2>&1
-
-	[ ! -e "/usr/share/$NAME/core/app.js" ] && { rm -f "/usr/share/$NAME/local_ver"; sh "/usr/share/$NAME/update.sh" "update_core_non_restart"; }
-	[ ! -e "/usr/share/$NAME/core/app.js" ] && { echo "Core Not Found, please download it before starting." >> "/tmp/$NAME.log"; exit 1; }
-
-	[ "${hijack_ways}" = "use_hosts" ] && { http_port="80"; https_port="443"; }
-	[ "${music_source}" = "default" ] && music_source="" || music_source="-o ${music_source}"
-	node "/usr/share/$NAME/core/app.js" -a "${addr}" -p "${http_port}":"${https_port}" ${music_source} -e "${endpoint_url}" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >> "/tmp/$NAME.log" 2>&1 &
-
-	set_type="start"
-	if [ "${hijack_ways}" = "use_ipset" ]; then
-		set_ipset > "/dev/null" 2>&1
-	elif [ "${hijack_ways}" = "use_hosts" ]; then
-		set_hosts > "/dev/null" 2>&1
-	fi
-	[ "$(uci_get_by_type "$NAME" pub_access)" = "1" ] && set_ports > "/dev/null" 2>&1
-}
+} >"/dev/null" 2>&1
 
 stop()
 {
 	{ ps |grep "$NAME" |grep "app.js" |grep -v "grep" |awk '{print $1}' |xargs kill -9; } > "/dev/null" 2>&1
 
+	config_load "$NAME"
+
 	sed -i "/$NAME/d" "/etc/crontabs/root"
 	/etc/init.d/cron restart > "/dev/null" 2>&1
 
-	[ ! -f "${UPGRADE_CONF}" ] && touch "${UPGRADE_CONF}"
-	sed -i "/$NAME\/core/d;/$NAME\/local_ver/d" "${UPGRADE_CONF}"
-	[ "${keep_core_when_upgrade}" -eq "1" ] && { echo "/usr/share/$NAME/core/" >> "${UPGRADE_CONF}"; echo "/usr/share/$NAME/local_ver" >> "${UPGRADE_CONF}"; }
+	[ -f "${UPGRADE_CONF}" ] && sed -i "/$NAME\/core/d;/$NAME\/local_ver/d" "${UPGRADE_CONF}"
+	is_enabled "config" "keep_core_when_upgrade" && { echo "/usr/share/$NAME/core/" >> "${UPGRADE_CONF}"; echo "/usr/share/$NAME/local_ver" >> "${UPGRADE_CONF}"; }
 
+	local self_issue_cert_crt self_issue_cert_key
+	config_get "self_issue_cert_crt" "config" "self_issue_cert_crt"
+	config_get "self_issue_cert_key" "config" "self_issue_cert_key"
 	{ [ -f "${self_issue_cert_crt}" ] && [ -f "${self_issue_cert_key}" ]; } && {
 		sed -i "/${self_issue_cert_crt//\//\\/}/d" "${UPGRADE_CONF}"
 		sed -i "/${self_issue_cert_key//\//\\/}/d" "${UPGRADE_CONF}"
@@ -234,10 +198,23 @@ stop()
 		echo "${self_issue_cert_key}" >> "${UPGRADE_CONF}"
 	}
 
-	rm -f "/tmp/$NAME.log"
+	http_port="$(cat "/tmp/$NAME.ports" | awk -F ':' 'print $1')"
+	https_port="$(cat "/tmp/$NAME.ports" | awk -F ':' 'print $2')"
+	iptables -D "INPUT" -p "tcp" --dport "${http_port}" -j "ACCEPT"
+	iptables -D "INPUT" -p "tcp" --dport "${https_port}" -j "ACCEPT"
 
-	set_type="stop"
-	set_ipset > "/dev/null" 2>&1
-	set_hosts > "/dev/null" 2>&1
-	set_ports > "/dev/null" 2>&1
-}
+	$IPT_N -D "PREROUTING" -p "tcp" -m set --match-set "neteasemusic" "dst" -j "netease_cloud_music"
+	$IPT_N -D "KOOLPROXY" -m "set" --match-set "neteasemusic" "dst" -j "RETURN" -m "comment" --comment "KP for UnblockMusic"
+	$IPT_N -F "netease_cloud_music"
+	$IPT_N -X "netease_cloud_music"
+	ipset destroy "neteasemusic"
+	ipset destroy "acl_neteasemusic_http"
+	ipset destroy "acl_neteasemusic_https"
+	echo "" > "/var/etc/$NAME.include"
+
+	rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
+	/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
+	ip route del "223.252.199.10"
+
+	rm -f "/tmp/$NAME.log"
+} >"/dev/null" 2>&1
